// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webshell.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunCmdWithOutputReq struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Language             string   `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Cmd                  string   `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunCmdWithOutputReq) Reset()         { *m = RunCmdWithOutputReq{} }
func (m *RunCmdWithOutputReq) String() string { return proto.CompactTextString(m) }
func (*RunCmdWithOutputReq) ProtoMessage()    {}
func (*RunCmdWithOutputReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcaa7cb24202361, []int{0}
}

func (m *RunCmdWithOutputReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunCmdWithOutputReq.Unmarshal(m, b)
}
func (m *RunCmdWithOutputReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunCmdWithOutputReq.Marshal(b, m, deterministic)
}
func (m *RunCmdWithOutputReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunCmdWithOutputReq.Merge(m, src)
}
func (m *RunCmdWithOutputReq) XXX_Size() int {
	return xxx_messageInfo_RunCmdWithOutputReq.Size(m)
}
func (m *RunCmdWithOutputReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RunCmdWithOutputReq.DiscardUnknown(m)
}

var xxx_messageInfo_RunCmdWithOutputReq proto.InternalMessageInfo

func (m *RunCmdWithOutputReq) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RunCmdWithOutputReq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *RunCmdWithOutputReq) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type RunCmdWithOutputRsp struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunCmdWithOutputRsp) Reset()         { *m = RunCmdWithOutputRsp{} }
func (m *RunCmdWithOutputRsp) String() string { return proto.CompactTextString(m) }
func (*RunCmdWithOutputRsp) ProtoMessage()    {}
func (*RunCmdWithOutputRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fcaa7cb24202361, []int{1}
}

func (m *RunCmdWithOutputRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunCmdWithOutputRsp.Unmarshal(m, b)
}
func (m *RunCmdWithOutputRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunCmdWithOutputRsp.Marshal(b, m, deterministic)
}
func (m *RunCmdWithOutputRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunCmdWithOutputRsp.Merge(m, src)
}
func (m *RunCmdWithOutputRsp) XXX_Size() int {
	return xxx_messageInfo_RunCmdWithOutputRsp.Size(m)
}
func (m *RunCmdWithOutputRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RunCmdWithOutputRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RunCmdWithOutputRsp proto.InternalMessageInfo

func (m *RunCmdWithOutputRsp) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*RunCmdWithOutputReq)(nil), "pb.RunCmdWithOutputReq")
	proto.RegisterType((*RunCmdWithOutputRsp)(nil), "pb.RunCmdWithOutputRsp")
}

func init() { proto.RegisterFile("webshell.ext.proto", fileDescriptor_5fcaa7cb24202361) }

var fileDescriptor_5fcaa7cb24202361 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4f, 0x4d, 0x2a,
	0xce, 0x48, 0xcd, 0xc9, 0xd1, 0x4b, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x52, 0x8a, 0xe6, 0x12, 0x0e, 0x2a, 0xcd, 0x73, 0xce, 0x4d, 0x09, 0xcf, 0x2c, 0xc9,
	0xf0, 0x2f, 0x2d, 0x29, 0x28, 0x2d, 0x09, 0x4a, 0x2d, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0x49, 0x2c,
	0x4a, 0x4f, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0xa4, 0xb8, 0x38,
	0x72, 0x12, 0xf3, 0xd2, 0x4b, 0x13, 0xd3, 0x53, 0x25, 0x98, 0xc0, 0x32, 0x70, 0xbe, 0x90, 0x00,
	0x17, 0x73, 0x72, 0x6e, 0x8a, 0x04, 0x33, 0x58, 0x18, 0xc4, 0x54, 0xd2, 0xc5, 0x62, 0x78, 0x71,
	0x01, 0xc8, 0xf0, 0x7c, 0x30, 0x07, 0x66, 0x38, 0x84, 0x67, 0x14, 0xc3, 0x25, 0x14, 0x0e, 0x75,
	0x65, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x6b, 0x45, 0x89, 0x90, 0x1b, 0x97, 0x00, 0xba,
	0x21, 0x42, 0xe2, 0x7a, 0x05, 0x49, 0x7a, 0x58, 0xdc, 0x2d, 0x85, 0x5d, 0xa2, 0xb8, 0x40, 0x89,
	0x21, 0x89, 0x0d, 0xec, 0x69, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x32, 0x9f, 0xb3,
	0x0a, 0x01, 0x00, 0x00,
}
