// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: webshell.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for WebshellServiceExt service

type WebshellServiceExtService interface {
	// Session会话
	// 传入可访问shell文件地址和对方服务器语言
	RunCmdWithOutput(ctx context.Context, in *RunCmdWithOutputReq, opts ...client.CallOption) (*RunCmdWithOutputRsp, error)
}

type webshellServiceExtService struct {
	c    client.Client
	name string
}

func NewWebshellServiceExtService(name string, c client.Client) WebshellServiceExtService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pb"
	}
	return &webshellServiceExtService{
		c:    c,
		name: name,
	}
}

func (c *webshellServiceExtService) RunCmdWithOutput(ctx context.Context, in *RunCmdWithOutputReq, opts ...client.CallOption) (*RunCmdWithOutputRsp, error) {
	req := c.c.NewRequest(c.name, "WebshellServiceExt.RunCmdWithOutput", in)
	out := new(RunCmdWithOutputRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WebshellServiceExt service

type WebshellServiceExtHandler interface {
	// Session会话
	// 传入可访问shell文件地址和对方服务器语言
	RunCmdWithOutput(context.Context, *RunCmdWithOutputReq, *RunCmdWithOutputRsp) error
}

func RegisterWebshellServiceExtHandler(s server.Server, hdlr WebshellServiceExtHandler, opts ...server.HandlerOption) error {
	type webshellServiceExt interface {
		RunCmdWithOutput(ctx context.Context, in *RunCmdWithOutputReq, out *RunCmdWithOutputRsp) error
	}
	type WebshellServiceExt struct {
		webshellServiceExt
	}
	h := &webshellServiceExtHandler{hdlr}
	return s.Handle(s.NewHandler(&WebshellServiceExt{h}, opts...))
}

type webshellServiceExtHandler struct {
	WebshellServiceExtHandler
}

func (h *webshellServiceExtHandler) RunCmdWithOutput(ctx context.Context, in *RunCmdWithOutputReq, out *RunCmdWithOutputRsp) error {
	return h.WebshellServiceExtHandler.RunCmdWithOutput(ctx, in, out)
}
